# Machine Learning
## Data Peprocessing

![logo](https://miro.medium.com/v2/resize:fit:720/format:webp/0*C_ibLD-RscbJzjMq.png)

In [49]:
import numpy as np
import pandas as pd

In [50]:
#importing dataset
dataset = pd.read_csv(r'C:\Users\HP\Dataml1.csv')
dataset

country   age   salary purchased
0   France  44.0  72000.0        no
1    Spain  27.0  48000.0       yes
2  Germany  30.0  54000.0        no
3    Spain  38.0  61000.0        no
4  Germany  40.0      NaN       yes
5   France  35.0  58000.0       yes
6    Spain   NaN  52000.0        no
7   France  48.0  79000.0       yes
8  Germany  50.0  83000.0        no
9   France  37.0  67000.0       yes

In [51]:
#independent variable x
x = dataset[['country','age','salary']]

In [52]:
print(x)
type(x)

   country   age   salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


pandas.core.frame.DataFrame

In [53]:
#converting x in array
x = dataset[['country','age','salary']].values

In [54]:
print(x)
type(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


numpy.ndarray

In [55]:
#dependent variable y and converting it into array
y = dataset[['purchased']].values

In [56]:
print(y)
type(y)

[['no']
 ['yes']
 ['no']
 ['no']
 ['yes']
 ['yes']
 ['no']
 ['yes']
 ['no']
 ['yes']]


numpy.ndarray

### Handling missing values

In [57]:
import sklearn
from sklearn.impute import SimpleImputer

In [59]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [61]:
imputer1 = imputer.fit(x[:,1:3])

In [62]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [63]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

### encoding Categorical data

In [64]:
from sklearn.preprocessing import LabelEncoder

In [65]:
label_encoder_x = LabelEncoder()     #LabelEncoder method

In [66]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [67]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

### Encoding using dummy encoder- OneHotEncoder()

In [68]:
from sklearn.preprocessing import OneHotEncoder

In [69]:
one_hot_encoder = OneHotEncoder()

In [72]:
x = one_hot_encoder.fit_transform(dataset.country.values.reshape(-1,1)).toarray()

In [73]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

### Encoding dependent variable y

In [74]:
label_encoder_y = LabelEncoder()

In [77]:
y = label_encoder_y.fit_transform(y)

In [76]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### Splitting data for train and test

In [79]:
from sklearn.model_selection import train_test_split

In [106]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [81]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [107]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [83]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [84]:
y_test

array([0, 0], dtype=int64)

### Feature Scaling

In [85]:
from sklearn.preprocessing import StandardScaler

In [86]:
sc_x = StandardScaler()

In [88]:
x_train = sc_x.fit_transform(x_train)

In [110]:
x_test = sc_x.transform(x_test)

In [90]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [111]:
x_test

array([[ 0., -1.,  0.],
       [ 0., -1.,  0.]])